# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b54839621114872c18c509eeb84ee7d32348a29319ebecaa44c2efa3c5152a9520f2437d64237d2910c8746184a486aa89157f3cd2952f8d082abae764ca1df2

test:
  secret_key_base: c1fdd64254a1d37a9b58166f77360c2f4a0245b365fe2e6c1d0d629c26d12fe0f9e59614eee0c50b58417f6d6ebb776c8ef954f92ca18da935bc8ad9a1173981

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
